### ISSUE TITLE
Seems not to work without jack.

### ISSUE THREAD

**Issue by mopsalarm** [skoumalcz/fragment-back#4] opened 2016-12-07 17:58 UTC
Gradle is giving me 
```Jack is disabled, but one of the plugins you are using supports Java 8 language features.```

I assume this is because of the constants defined on an interface.

**Comment by gingo** [comment] 2016-12-07 18:05
Are you sure this error is caused by FragmentBack? I do not have Java 8 support installed on my primary dev machine and it works fine for me.

**Comment by mopsalarm** [comment] 2016-12-07 18:09
Yes you are right. I was a little bit too fast there. After adding the library to my project, i can not find any of the classes in android studio. The expect the gradle import to work - I checked by miss-typing the gradle-coordinates which led to an error.

**Comment by gingo** [comment] 2016-12-07 18:41
Ok, I'm closing issue for now. Feel free to reopen or create new one in case of other problems.

**Closed by gingo** 2016-12-07 18:41 UTC
